<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CatalogProduct.proto

namespace Catalog;

if (false) {
    /**
     * This class is deprecated. Use Catalog\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Catalog\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Catalog\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

