<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Warehouse.proto

namespace Warehouse;

if (false) {
    /**
     * This class is deprecated. Use Warehouse\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Warehouse\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Warehouse\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

