<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Warehouse.proto

namespace Warehouse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>warehouse.verifyStockRequest</code>
 */
class verifyStockRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 warehouseId = 1;</code>
     */
    protected $warehouseId = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $warehouseId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Warehouse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 warehouseId = 1;</code>
     * @return int
     */
    public function getWarehouseId()
    {
        return $this->warehouseId;
    }

    /**
     * Generated from protobuf field <code>int32 warehouseId = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setWarehouseId($var)
    {
        GPBUtil::checkInt32($var);
        $this->warehouseId = $var;

        return $this;
    }

}

