<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Order.proto

namespace GPBMetadata;

class Order
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
™
Order.protoorder"
Request
jsonData (	"
Response
message (	2A
OrderService1
uploadTracking.order.Request.order.Responsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

