<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Fulfillment.proto

namespace Fulfillment;

if (false) {
    /**
     * This class is deprecated. Use Fulfillment\HealthCheckResponse\ServingStatus instead.
     * @deprecated
     */
    class HealthCheckResponse_ServingStatus {}
}
class_exists(HealthCheckResponse\ServingStatus::class);
@trigger_error('Fulfillment\HealthCheckResponse_ServingStatus is deprecated and will be removed in the next major release. Use Fulfillment\HealthCheckResponse\ServingStatus instead', E_USER_DEPRECATED);

